### ISSUE TITLE
Getting all CI jobs to pass should be prio one for now

### ISSUE THREAD

**Issue by ChillerDragon** [teeworlds-community/teeworlds#77]
Currently windows and macOS build are failing.

**Comment by MilkeeyCat** [comment]
LGTM :rocket:

**Comment by ChillerDragon** [comment]
There are a lot of deprecation warnings in the code triggering -Werror. But this macOS build error seems to be a low hanging fruit.

```
Run sudo python3 scripts/make_release.py master macos
Traceback (most recent call last):
  File "/Users/runner/work/teeworlds/teeworlds/scripts/make_release.py", line 2, in <module>
    from distutils.dir_util import copy_tree
ModuleNotFoundError: No module named 'distutils'
Error: Process completed with exit code 1.
```

https://github.com/teeworlds-community/teeworlds/actions/runs/8018802243/job/21905439792

https://peps.python.org/pep-0632/

**Comment by Bamcane** [comment]
I tried to fix CI in TeeGlue, but it failed, because i use `override` on my project, the macOS CI had a problem: You need use override to take every virtual function's place in the child classes, maybe we need add more c++11 features on this problem

**Comment by jtbx** [comment]
> There are a lot of deprecation warnings in the code triggering -Werror. But this macOS build error seems to be a low hanging fruit.

Why even is -Werror used? Using it in CI seems like a way to cause
problems down the line.

**Comment by ChillerDragon** [comment]
> Why even is -Werror used? Using it in CI seems like a way to cause
> problems down the line.

Yes that's the idea behind a CI. It should cause problems there so when it passes you know nobody runs into any warnings locally when compiling.

**Comment by Bamcane** [comment]
> > Why even is -Werror used? Using it in CI seems like a way to cause
> > problems down the line.
> 
> Yes that's the idea behind a CI. It should cause problems there so when it passes you know nobody runs into any warnings locally when compiling.

@ChillerDragon 
There's a warning on Arch Linux, because of `engine/graphics.h`, a line of it use `set_size(0)`, we all know it will not be alloc, but gcc 13.2.1 didn't think so

**Comment by ChillerDragon** [comment]
Weird on my mac installing setup tools fixes the distutils issue. 

```
ChillersMacBookPro:teeworlds chillerdragon$ python3
Python 3.12.2 (v3.12.2:6abddd9f6a, Feb  6 2024, 17:02:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils.dir_util import copy_tree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'distutils'
>>> ^D
ChillersMacBookPro:teeworlds chillerdragon$ pip install setuptools
Collecting setuptools
  Using cached setuptools-69.1.1-py3-none-any.whl.metadata (6.2 kB)
Using cached setuptools-69.1.1-py3-none-any.whl (819 kB)
Installing collected packages: setuptools
Successfully installed setuptools-69.1.1
ChillersMacBookPro:teeworlds chillerdragon$ python3
Python 3.12.2 (v3.12.2:6abddd9f6a, Feb  6 2024, 17:02:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from distutils.dir_util import copy_tree
>>> 
```

So I tried the same in the CI and that somehow did not work. https://github.com/teeworlds-community/teeworlds/actions/runs/8036493796/job/21950256686

**Comment by MilkeeyCat** [comment]
> Traceback (most recent call last):
>   File "D:\a\teeworlds\teeworlds\scripts\download.py", line 2, in <module>
>     from distutils.dir_util import copy_tree
> ModuleNotFoundError: No module named 'distutils'

yo dawgs, that's why windows ci doenst work

**Comment by MilkeeyCat** [comment]
can we close dis?

**Comment by ChillerDragon** [comment]
yes :partying_face:
